# Generated by Django 5.0.9 on 2024-10-04 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'cafe_payments',
            },
        ),
    ]
